### ISSUE TITLE
Windows Defender High CPU/CLI Command Doesn't Finish

### ISSUE THREAD

**Issue by geonerdist** [AaronPLopez/SystemLogParser#2]
I have setup SLP to run via command line automatically on my workstation once a week. I am trying to move this process to a server but it never seems to finish running. Looking at Task Manager on this server the Antimalware Service Executable (Windows Defender Service) has constant high CPU utilization. Most times it's greater than 15% but can jump up to over 50%. It takes about 15 minutes to run on my workstation, I usually cancel the script at about an hour of running. I have added my custom download directory, installation directory, and script directory as exclusions in the Windows Defender excluded folders.

**Comment by geonerdist** [comment]
Looks like my download location didn't save as an excluded folder. SLP command finished successfully.

**Comment by AaronPLopez** [comment]
Hi Curtis,
> I am trying to move this process to a server but it never seems to finish
running
Some things which may help speed up the log parsing process when running
the log parsing directly on the server:

   - It is recommended to use the ArcGIS Server File System query. This
   will be much faster than querying through the Web.
   - Use the Optimized Analysis Type report. The Optimized report is faster
   and utilizes memory much more effectively (by orders of magnitude).
   - The latest System Log Parser builds sign all exes and dlls. This might
   help improve the resource utilization with some Antimalware scans.


Aaron

**Comment by geonerdist** [comment]
Thank you Aaron. I am using the File System and Optimized report. I'll make sure I have the latest build.

I think this issue might be a Windows problem. I have my SLP command in a batch file that I'm starting from Task Scheduler. When this batch file is ran from Task Scheduler is when it never seems to to finish (I've let it run for about 4 hours before cancelling). When I run it by open the batch file through File Explorer, it runs and finishes in about 15-20 minutes.
