### ISSUE TITLE
json report type

### ISSUE THREAD

**Issue by azinsharaf** [AaronPLopez/SystemLogParser#4]
when I use `JSON` as report type, the JSON content would be printed in terminal but no json file is created. Is it normal?

**Comment by AaronPLopez** [comment]
Hello Azin,
Yes, that is normal and expected behavior. This feature was built to pipe
the JSON output into listeners.
If you require a file, you should be able to redirect the JSON output with:
"command > myfile.json"

Thanks.
Aaron

**Comment by azinsharaf** [comment]
Thanks. I use the redirect then.
